### PR TITLE
Store iptables when creating network attack

### LINKED ISSUE #213: network partition doesn't work when network delay was applied in advance

### PR DESCRIPTION
**Pull request by FingerLeader**
Signed-off-by: root <root@localhost.localdomain>
Close #213

### CODE REVIEW

**Comment by cwen0** [comment]
@FingerLeader I test this pr on my environment, I found the network delay still cancel when I applied a partition action.  

```
./bin/chaosd version
Chaosd Version: version.Info{GitVersion:"fix-partition-g83eccfacc55fe7", GitCommit:"83eccfacc55fe7a29c102df7cb05daa2ea1ac00f", BuildDate:"2022-09-13T15:03:27Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"} 
./bin/chaosd attack network delay -i 39.156.66.10 -d eth0 -l 200ms
./bin/chaosd attack network partition -i 140.205.220.96 -d eth0
```
image

**Comment by FingerLeader** [comment]
> I found the network delay still cancel when I applied a partition action.
> 
> ```
> ./bin/chaosd version
> ```

I test it again and find it works. Maybe you can delete `./bin/chaosd.dat` and try again.

**Comment by cwen0** [comment]
> > I found the network delay still cancel when I applied a partition action.
> > ```
> > ./bin/chaosd version
> > ```
> 
> I test it again and find it works. Maybe you can delete `./bin/chaosd.dat` and try again.

OK, I will test it again

File: pkg/server/chaosd/network.go [hunk 1]
```diff
@@ -79,11 +79,9 @@ func (networkAttack) Attack(options core.AttackConfig, env Environment) (err err
 				return perrors.WithStack(err)
```
Comment (cwen0) [inline pkg/server/chaosd/network.go:79]: We can delete `NeedApplyIptables()` and `NeedApplyIPSet` directly.

File: pkg/server/chaosd/network.go [hunk 2]
```diff
@@ -380,22 +389,20 @@ func (networkAttack) Recover(exp core.Experiment, env Environment) error {
 	case core.NetworkPortOccupiedAction:
 		return env.Chaos.recoverPortOccupied(attack, env.AttackUid)
 	case core.NetworkDelayAction, core.NetworkLossAction, core.NetworkCorruptAction, core.NetworkDuplicateAction, core.NetworkPartitionAction, core.NetworkBandwidthAction:
-		if attack.NeedApplyIPSet() {
-			if err := env.Chaos.recoverIPSet(env.AttackUid); err != nil {
-				return perrors.WithStack(err)
-			}
+		// `chaosdaemon.DeamonServer.SetTcs()` may build new iptables which will not be recorded in DB,
```
Comment (cwen0) [inline pkg/server/chaosd/network.go:392]: We should update this comment.

File: pkg/server/chaosd/network.go (hunk 1 above)
Comment (FingerLeader) [reply pkg/server/chaosd/network.go:79]: I think leaving them can make the code logic clearly, and they may be needed to add features later (by the way, `NeedApplyIPSet()` is working now)

File: pkg/server/chaosd/network.go (hunk 2 above)
Comment (FingerLeader) [reply pkg/server/chaosd/network.go:392]: I don't think this comment should be updated, the filter iptables still not be stored in the DB

File: pkg/server/chaosd/network.go (hunk 1 above)
Comment (cwen0) [reply pkg/server/chaosd/network.go:79]: I think the logic will be clearer If we delete them. The logic: Chaos Mesh will reset all network action when you apply the network actions. This logic will be more simple.

File: pkg/server/chaosd/network.go (hunk 2 above)
Comment (cwen0) [reply pkg/server/chaosd/network.go:392]: Yes, but here we recover all because chaos mesh will apply all network actions when we apply a new one.

File: pkg/server/chaosd/network.go (hunk 1 above)
Comment (FingerLeader) [reply pkg/server/chaosd/network.go:79]: OK, I think it's OK to be the same as chaos mesh, `NeedApplyIptables` can be deleted, but I find `chaosd attack network delay -l 1s -d eth0` will not work without `NeedApplyIPSet()`

File: pkg/server/chaosd/network.go (hunk 2 above)
Comment (FingerLeader) [reply pkg/server/chaosd/network.go:392]: I agree

**Review by cwen0 — APPROVED** [review]
LGTM
